In [1]:
import pandas as pd
import numpy as np
from google.colab import files

In [ ]:
dataset = pd.read_csv('sample_data/kidney_disease.csv')

In [ ]:
dataset.head()

id   age    bp     sg   al   su  ...   dm cad appet   pe  ane  classification
0   0  48.0  80.0  1.020  1.0  0.0  ...  yes  no  good   no   no             ckd
1   1   7.0  50.0  1.020  4.0  0.0  ...   no  no  good   no   no             ckd
2   2  62.0  80.0  1.010  2.0  3.0  ...  yes  no  poor   no  yes             ckd
3   3  48.0  70.0  1.005  4.0  0.0  ...   no  no  poor  yes  yes             ckd
4   4  51.0  80.0  1.010  2.0  0.0  ...   no  no  good   no   no             ckd

[5 rows x 26 columns]

In [ ]:
dataset.shape

(400, 26)

In [ ]:
dataset[['htn','dm','cad','pe','ane']]=dataset[['htn','dm','cad','pe','ane']].replace(to_replace={'yes':1,'no':0})
dataset[['rbc','pc']] = dataset[['rbc','pc']].replace(to_replace={'abnormal':0,'normal':1})
dataset[['pcc','ba']] = dataset[['pcc','ba']].replace(to_replace={'present':1,'notpresent':0})
dataset[['appet']] = dataset[['appet']].replace(to_replace={'good':1,'poor':0,'no':np.nan})
dataset['classification']=dataset['classification'].replace(to_replace={'ckd':1.0,'ckd\t':1.0,'notckd':0.0,'no':0.0})
dataset.rename(columns={'classification':'class'},inplace=True)

In [ ]:
# Further cleaning
dataset['pe'] = dataset['pe'].replace(to_replace='good',value=0) # Not having pedal edema is good
dataset['appet'] = dataset['appet'].replace(to_replace='no',value=0)
dataset['cad'] = dataset['cad'].replace(to_replace='\tno',value=0)
dataset['dm'] = dataset['dm'].replace(to_replace={'\tno':0,'\tyes':1,' yes':1, '':np.nan})
dataset.drop('id',axis=1,inplace=True)

In [ ]:
dataset.head()

age    bp     sg   al   su  rbc   pc  ...  htn   dm  cad  appet   pe  ane  class
0  48.0  80.0  1.020  1.0  0.0  NaN  1.0  ...  1.0  1.0  0.0    1.0  0.0  0.0    1.0
1   7.0  50.0  1.020  4.0  0.0  NaN  1.0  ...  0.0  0.0  0.0    1.0  0.0  0.0    1.0
2  62.0  80.0  1.010  2.0  3.0  1.0  1.0  ...  0.0  1.0  0.0    0.0  0.0  1.0    1.0
3  48.0  70.0  1.005  4.0  0.0  1.0  0.0  ...  1.0  0.0  0.0    0.0  1.0  1.0    1.0
4  51.0  80.0  1.010  2.0  0.0  1.0  1.0  ...  0.0  0.0  0.0    1.0  0.0  0.0    1.0

[5 rows x 25 columns]

In [ ]:
# '?' character remove process in the dataset
for i in ['rc','wc','pcv']:
    dataset[i] = dataset[i].str.extract('(\d+)').astype(float)

In [ ]:
# Filling missing numeric data in the dataset with mean
for i in ['age','bp','sg','al','su','bgr','bu','sc','sod','pot','hemo','rc','wc','pcv']:
    dataset[i].fillna(dataset[i].mean(),inplace=True)

In [ ]:
dataset.isnull().sum()

age        0
bp         0
sg         0
al         0
su         0
rbc      152
pc        65
pcc        4
ba         4
bgr        0
bu         0
sc         0
sod        0
pot        0
hemo       0
pcv        0
wc         0
rc         0
htn        2
dm         2
cad        2
appet      1
pe         1
ane        1
class      0
dtype: int64

In [ ]:
dataset.shape

(400, 25)

In [ ]:
dataset = dataset.dropna(axis=1)

In [ ]:
dataset.shape

(400, 15)

In [ ]:
dataset.isnull().sum()

age      0
bp       0
sg       0
al       0
su       0
bgr      0
bu       0
sc       0
sod      0
pot      0
hemo     0
pcv      0
wc       0
rc       0
class    0
dtype: int64

In [ ]:
dataset.head()

age    bp     sg   al   su  ...  hemo   pcv      wc        rc  class
0  48.0  80.0  1.020  1.0  0.0  ...  15.4  44.0  7800.0  5.000000    1.0
1   7.0  50.0  1.020  4.0  0.0  ...  11.3  38.0  6000.0  4.241636    1.0
2  62.0  80.0  1.010  2.0  3.0  ...   9.6  31.0  7500.0  4.241636    1.0
3  48.0  70.0  1.005  4.0  0.0  ...  11.2  32.0  6700.0  3.000000    1.0
4  51.0  80.0  1.010  2.0  0.0  ...  11.6  35.0  7300.0  4.000000    1.0

[5 rows x 15 columns]

In [ ]:
dataset

age    bp     sg   al   su  ...  hemo   pcv      wc        rc  class
0    48.0  80.0  1.020  1.0  0.0  ...  15.4  44.0  7800.0  5.000000    1.0
1     7.0  50.0  1.020  4.0  0.0  ...  11.3  38.0  6000.0  4.241636    1.0
2    62.0  80.0  1.010  2.0  3.0  ...   9.6  31.0  7500.0  4.241636    1.0
3    48.0  70.0  1.005  4.0  0.0  ...  11.2  32.0  6700.0  3.000000    1.0
4    51.0  80.0  1.010  2.0  0.0  ...  11.6  35.0  7300.0  4.000000    1.0
..    ...   ...    ...  ...  ...  ...   ...   ...     ...       ...    ...
395  55.0  80.0  1.020  0.0  0.0  ...  15.7  47.0  6700.0  4.000000    0.0
396  42.0  70.0  1.025  0.0  0.0  ...  16.5  54.0  7800.0  6.000000    0.0
397  12.0  80.0  1.020  0.0  0.0  ...  15.8  49.0  6600.0  5.000000    0.0
398  17.0  60.0  1.025  0.0  0.0  ...  14.2  51.0  7200.0  5.000000    0.0
399  58.0  80.0  1.025  0.0  0.0  ...  15.8  53.0  6800.0  6.000000    0.0

[400 rows x 15 columns]

In [ ]:
dataset.iloc[:,:-1]

age    bp     sg   al   su  ...       pot  hemo   pcv      wc        rc
0    48.0  80.0  1.020  1.0  0.0  ...  4.627244  15.4  44.0  7800.0  5.000000
1     7.0  50.0  1.020  4.0  0.0  ...  4.627244  11.3  38.0  6000.0  4.241636
2    62.0  80.0  1.010  2.0  3.0  ...  4.627244   9.6  31.0  7500.0  4.241636
3    48.0  70.0  1.005  4.0  0.0  ...  2.500000  11.2  32.0  6700.0  3.000000
4    51.0  80.0  1.010  2.0  0.0  ...  4.627244  11.6  35.0  7300.0  4.000000
..    ...   ...    ...  ...  ...  ...       ...   ...   ...     ...       ...
395  55.0  80.0  1.020  0.0  0.0  ...  4.900000  15.7  47.0  6700.0  4.000000
396  42.0  70.0  1.025  0.0  0.0  ...  3.500000  16.5  54.0  7800.0  6.000000
397  12.0  80.0  1.020  0.0  0.0  ...  4.400000  15.8  49.0  6600.0  5.000000
398  17.0  60.0  1.025  0.0  0.0  ...  4.900000  14.2  51.0  7200.0  5.000000
399  58.0  80.0  1.025  0.0  0.0  ...  3.500000  15.8  53.0  6800.0  6.000000

[400 rows x 14 columns]

In [ ]:
dataset.iloc[:,-1]

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ... 
395    0.0
396    0.0
397    0.0
398    0.0
399    0.0
Name: class, Length: 400, dtype: float64

In [ ]:
# Data preprocessing
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
from sklearn.model_selection import train_test_split    
from sklearn.preprocessing import MinMaxScaler

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [ ]:
scaler = MinMaxScaler()

In [ ]:
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.svm import SVC

In [ ]:
svm = SVC()
svm.fit(X_train, y_train)
predictions = svm.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.93      1.00      0.97        28
         1.0       1.00      0.96      0.98        52

    accuracy                           0.97        80
   macro avg       0.97      0.98      0.97        80
weighted avg       0.98      0.97      0.98        80

[[28  0]
 [ 2 50]]


In [ ]:
abc = AdaBoostClassifier(n_estimators=100, random_state=0)
abc.fit(X_train, y_train)
predictions = abc.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.97      1.00      0.98        28
         1.0       1.00      0.98      0.99        52

    accuracy                           0.99        80
   macro avg       0.98      0.99      0.99        80
weighted avg       0.99      0.99      0.99        80

[[28  0]
 [ 1 51]]


In [ ]:
rfc = RandomForestClassifier(max_depth=2, random_state=0)
rfc.fit(X_train, y_train)
predictions = rfc.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.96      0.96      0.96        28
         1.0       0.98      0.98      0.98        52

    accuracy                           0.97        80
   macro avg       0.97      0.97      0.97        80
weighted avg       0.97      0.97      0.97        80

[[27  1]
 [ 1 51]]
