In [ ]:
import pandas as pd
import numpy as np
from google.colab import files

In [ ]:
!pip install tensorflow==2.5

In [ ]:
!pip install keras==2.4.3

In [ ]:
dataset = pd.read_csv('sample_data/data_CKD_bigdata_refined.csv')

In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')

In [ ]:
dataset.head()

sex   age  sido  height  ...  MOUTH_CHECK        BMI         GFR  stage
0  1.0   8.0  43.0   170.0  ...          1.0  25.951557   86.886038      2
1  1.0   7.0  11.0   180.0  ...          1.0  24.691358  100.644197      1
2  1.0   9.0  41.0   165.0  ...          0.0  27.548209   95.928640      1
3  1.0  11.0  48.0   175.0  ...          1.0  26.122449   73.203730      2
4  1.0  11.0  30.0   165.0  ...          1.0  22.038567  105.714492      1

[5 rows x 29 columns]

In [ ]:
#dataset=dataset.drop(['pot','pcc','ba','cad','ane'],1)##boruta

In [ ]:
#dataset=dataset[['sg', 'al', 'hemo', 'pcv', 'htn', 'dm','class']]#lasso

In [ ]:
#dataset=dataset.drop(['age','bp','sg','al','su','bgr','wc','appet','pe','ane'],1)#rfe

In [ ]:
  #dataset=dataset[['htn',	'sg',	'rbc','dm','rc','al','appet','pe','ane', 'pc','bp','class']]#cfs

In [ ]:
dataset

sex   age  sido  height  ...  MOUTH_CHECK        BMI         GFR  stage
0       1.0   8.0  43.0   170.0  ...          1.0  25.951557   86.886038      2
1       1.0   7.0  11.0   180.0  ...          1.0  24.691358  100.644197      1
2       1.0   9.0  41.0   165.0  ...          0.0  27.548209   95.928640      1
3       1.0  11.0  48.0   175.0  ...          1.0  26.122449   73.203730      2
4       1.0  11.0  30.0   165.0  ...          1.0  22.038567  105.714492      1
...     ...   ...   ...     ...  ...          ...        ...         ...    ...
999995  1.0  10.0  48.0   175.0  ...          0.0  26.122449   83.237802      2
999996  1.0   8.0  41.0   170.0  ...          0.0  25.951557   77.836416      2
999997  2.0   9.0  26.0   155.0  ...          0.0  20.811655   81.542158      2
999998  1.0   6.0  29.0   175.0  ...          0.0  19.591837  118.695643      1
999999  1.0  11.0  41.0   160.0  ...          0.0  27.343750   92.279348      1

[1000000 rows x 29 columns]

In [ ]:
#dataset.shape

In [ ]:
#dataset[['htn','dm','cad','pe','ane']]=dataset[['htn','dm','cad','pe','ane']].replace(to_replace={'yes':1,'no':0})
#dataset[['rbc','pc']] = dataset[['rbc','pc']].replace(to_replace={'abnormal':1,'normal':0})
#dataset[['pcc','ba']] = dataset[['pcc','ba']].replace(to_replace={'present':1,'notpresent':0})
#dataset[['appet']] = dataset[['appet']].replace(to_replace={'good':1,'poor':0,'no':np.nan})
#dataset['classification']=dataset['classification'].replace(to_replace={'ckd':1.0,'ckd\t':1.0,'notckd':0.0,'no':0.0})
#dataset.rename(columns={'classification':'class'},inplace=True)

In [ ]:
# # Further cleaning
# dataset['pe'] = dataset['pe'].replace(to_replace='good',value=0) # Not having pedal edema is good
# dataset['appet'] = dataset['appet'].replace(to_replace='no',value=0)
# dataset['cad'] = dataset['cad'].replace(to_replace='\tno',value=0)
# dataset['dm'] = dataset['dm'].replace(to_replace={'\tno':0,'\tyes':1,' yes':1, '':np.nan})
# dataset.drop('id',axis=1,inplace=True)

In [ ]:
#dataset.head()

In [ ]:
# '?' character remove process in the dataset
#for i in ['rc','wc','pcv']:
    #dataset[i] = dataset[i].str.extract('(\d+)').astype(float)

In [ ]:
# Filling missing numeric data in the dataset with mean
#for i in ['age','bp','sg','al','su','bgr','bu','sc','sod','pot','hemo','rc','wc','pcv']:
    #dataset[i].fillna(dataset[i].mean(),inplace=True)

In [ ]:
#dataset.isnull().sum()

In [ ]:
#dataset = dataset.dropna(axis=1)

In [ ]:
dataset.head()

sex   age  sido  height  ...  MOUTH_CHECK        BMI         GFR  stage
0  1.0   8.0  43.0   170.0  ...          1.0  25.951557   86.886038      2
1  1.0   7.0  11.0   180.0  ...          1.0  24.691358  100.644197      1
2  1.0   9.0  41.0   165.0  ...          0.0  27.548209   95.928640      1
3  1.0  11.0  48.0   175.0  ...          1.0  26.122449   73.203730      2
4  1.0  11.0  30.0   165.0  ...          1.0  22.038567  105.714492      1

[5 rows x 29 columns]

In [ ]:
dataset.shape

(1000000, 29)

In [ ]:
#dataset.isnull().sum()

In [ ]:
#dataset.head()

In [ ]:
#dataset=dataset.drop('class',1)

In [ ]:
#dataset.iloc[:,:-1]

In [ ]:
dataset.iloc[:,-1]

0         2
1         1
2         1
3         2
4         1
         ..
999995    2
999996    2
999997    2
999998    1
999999    1
Name: stage, Length: 1000000, dtype: int64

In [ ]:
# Data preprocessing
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
X

array([[  1.        ,   8.        ,  43.        , ...,   1.        ,
         25.95155709,  86.88603751],
       [  1.        ,   7.        ,  11.        , ...,   1.        ,
         24.69135802, 100.6441974 ],
       [  1.        ,   9.        ,  41.        , ...,   0.        ,
         27.54820937,  95.92863959],
       ...,
       [  2.        ,   9.        ,  26.        , ...,   0.        ,
         20.81165453,  81.54215818],
       [  1.        ,   6.        ,  29.        , ...,   0.        ,
         19.59183673, 118.6956429 ],
       [  1.        ,  11.        ,  41.        , ...,   0.        ,
         27.34375   ,  92.27934768]])

In [ ]:
y

array([2, 1, 1, ..., 2, 1, 1])

In [ ]:
from sklearn.model_selection import train_test_split    
from sklearn.preprocessing import MinMaxScaler

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [ ]:
X_train

array([[  2.        ,  13.        ,  41.        , ...,   0.        ,
         21.484375  , 105.8233829 ],
       [  2.        ,   9.        ,  43.        , ...,   1.        ,
         24.22145329,  81.54215818],
       [  2.        ,  10.        ,  26.        , ...,   1.        ,
         29.13631634, 111.3622426 ],
       ...,
       [  2.        ,   9.        ,  41.        , ...,   0.        ,
         27.05515088, 113.6479232 ],
       [  1.        ,  10.        ,  44.        , ...,   1.        ,
         27.34375   , 107.684888  ],
       [  2.        ,  12.        ,  41.        , ...,   1.        ,
         27.05515088,  77.12361198]])

In [ ]:
X_train.shape

(800000, 28)

In [ ]:
scaler = MinMaxScaler()

In [ ]:
X_test.shape

(200000, 28)

In [ ]:
y_test.shape

(200000,)

In [ ]:
y_test

array([2, 1, 2, ..., 2, 1, 2])

In [ ]:
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

In [ ]:
# # Reshaping X_train for efficient modelling
# X_train = np.reshape(X_train, (X_train.shape[0],X_train.shape[1],1))
# X_test = np.reshape(X_test, (X_test.shape[0],X_test.shape[1],1))

In [ ]:
from keras.models import Sequential
from tensorflow import keras
from keras.layers import Dense, LSTM, Dropout, GRU, Bidirectional
#from keras.optimizers import SGD
import math
from sklearn.metrics import mean_squared_error

In [ ]:
import time
start_time = time.time()
#build the model
# sequential
#3 layers firtst 2 nurons and relu function
#output layer 10 nuron softmax function
model = Sequential()
model.add(keras.layers.Dense (15,input_shape=(X_train.shape[1],),activation='relu')) #input layer
model.add(keras.layers.Dense (10,activation='relu')) #hidden
model.add(keras.layers.Dense (1,activation='sigmoid')) #output
model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)
model.fit(X_train,y_train,epochs=200,validation_data=(X_test, y_test))
print("--- %s seconds ---" % (time.time() - start_time))

In [ ]:
#from keras.utils.vis_utils import plot_model
#plot_model(model, to_file='model_plot_ann_wfs.png')

In [ ]:
# from google.colab import files
# files.download('model_plot_ann_wfs.png') 

In [ ]:
import matplotlib.pyplot as plt

fig = plt.gcf()
plt.plot(model.history.history['loss'])
plt.plot(model.history.history['val_loss'])
plt.title('ANN-WFS')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend(['loss', 'validation loss'], loc='upper right')
plt.show()
fig.savefig('ANN-WFS.png', dpi=100)

In [ ]:
from google.colab import files
files.download('ANN-WFS.png') 

In [ ]:
predictions = model.predict_classes(X_test)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
print(classification_report(y_test,predictions))

In [ ]:
print(confusion_matrix(y_test,predictions))

In [ ]:
cnf_matrix = [[28, 0],[3, 49]]

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

class_names = [0,1]
fig,ax = plt.subplots()
tick_marks = np.arange(len(class_names))
plt.xticks(tick_marks,class_names)
plt.yticks(tick_marks,class_names)

#create a heat map
sns.heatmap(pd.DataFrame(cnf_matrix), annot = True,cmap = 'YlGnBu',
           fmt = 'g')
ax.xaxis.set_label_position('top')
plt.tight_layout()
plt.title('ANN_WFS', y = 1.1)
plt.ylabel('Actual label')
plt.xlabel('Predicted label')
plt.savefig('ANN_WFS_Matrix.png')
plt.show()

In [ ]:
from sklearn.metrics import accuracy_score
first = 0
second = 50
prediction_accuracy = []
for i in range(8):
  X_test_ = dataset.iloc[first:second,:-1].values
  y_true = dataset.iloc[first:second,-1].values

  #X_test_  = scaler.transform(X_test_)

  y_pred = model.predict_classes(X_test_)
  accuracy = accuracy_score(y_true, y_pred)
  prediction_accuracy.append(accuracy)

  first = second
  second = second+50
prediction_accuracy

In [ ]:
from sklearn.metrics import roc_curve, auc
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, predictions)
roc_auc = auc(false_positive_rate, true_positive_rate)
roc_auc

In [ ]:
import matplotlib.pyplot as plt
plt.figure(figsize=(10,10))
plt.title('ANN_WFS')
plt.plot(false_positive_rate,true_positive_rate, color='red',label = 'AUC = %0.2f' % roc_auc)
plt.legend(loc = 'lower right')
plt.plot([0, 1], [0, 1],linestyle='--')
plt.axis('tight')
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')


In [ ]:
data = {
    'ANN_false': false_positive_rate,
    'ANN_true': true_positive_rate,
    'ANN_prediction_accuracy': prediction_accuracy
  }

In [ ]:
df = pd.DataFrame.from_dict(data, orient='index')
df = df.transpose()

In [ ]:
#df.to_csv('ann_WFS_output.csv', index=False)

In [ ]:
#from google.colab import files
#files.download('ann_WFS_output.csv') 