In [1]:
import pandas as pd
import numpy as np
from google.colab import files

In [2]:
!pip install tensorflow==2.5

In [3]:
!pip install keras==2.4.3

In [4]:
dataset = pd.read_csv('sample_data/data_CKD_MI.csv')

In [5]:
#from google.colab import drive
#drive.mount('/content/drive')

In [6]:
dataset.head()

age    bp     sg   al   su         bgr  ...   dm  cad  appet   pe  ane  class
0  48.0  80.0  1.020  1.0  0.0  121.000000  ...  1.0  0.0    1.0  0.0  0.0    1.0
1   7.0  50.0  1.020  4.0  0.0  151.688303  ...  0.0  0.0    1.0  0.0  0.0    1.0
2  62.0  80.0  1.010  2.0  3.0  423.000000  ...  1.0  0.0    0.0  0.0  1.0    1.0
3  48.0  70.0  1.005  4.0  0.0  117.000000  ...  0.0  0.0    0.0  1.0  1.0    1.0
4  51.0  80.0  1.010  2.0  0.0  106.000000  ...  0.0  0.0    1.0  0.0  0.0    1.0

[5 rows x 25 columns]

In [7]:
#dataset=dataset.drop(['pot','pcc','ba','cad','ane'],1)##boruta

In [8]:
#dataset=dataset[['sg', 'al', 'hemo', 'pcv', 'htn', 'dm','class']]#lasso

In [9]:
dataset=dataset.drop(['age','bp','sg','al','su','bgr','wc','appet','pe','ane'],1)#rfe

In [10]:
  #dataset=dataset[['htn',	'sg',	'rbc','dm','rc','al','appet','pe','ane', 'pc','bp','class']]#cfs

In [11]:
dataset

bu   sc         sod       pot  hemo  ...   ba  htn   dm  cad  class
0    36.0  1.2  138.672705  3.728215  15.4  ...  0.0  1.0  1.0  0.0    1.0
1    18.0  0.8  130.739113  3.874993  11.3  ...  0.0  0.0  0.0  0.0    1.0
2    53.0  1.8  132.762387  4.944903   9.6  ...  0.0  0.0  1.0  0.0    1.0
3    56.0  3.8  111.000000  2.500000  11.2  ...  0.0  1.0  0.0  0.0    1.0
4    26.0  1.4  133.960632  3.462571  11.6  ...  0.0  0.0  0.0  0.0    1.0
..    ...  ...         ...       ...   ...  ...  ...  ...  ...  ...    ...
395  49.0  0.5  150.000000  4.900000  15.7  ...  0.0  0.0  0.0  0.0    0.0
396  31.0  1.2  141.000000  3.500000  16.5  ...  0.0  0.0  0.0  0.0    0.0
397  26.0  0.6  137.000000  4.400000  15.8  ...  0.0  0.0  0.0  0.0    0.0
398  50.0  1.0  135.000000  4.900000  14.2  ...  0.0  0.0  0.0  0.0    0.0
399  18.0  1.1  141.000000  3.500000  15.8  ...  0.0  0.0  0.0  0.0    0.0

[400 rows x 15 columns]

In [12]:
#dataset.shape

In [13]:
#dataset[['htn','dm','cad','pe','ane']]=dataset[['htn','dm','cad','pe','ane']].replace(to_replace={'yes':1,'no':0})
#dataset[['rbc','pc']] = dataset[['rbc','pc']].replace(to_replace={'abnormal':1,'normal':0})
#dataset[['pcc','ba']] = dataset[['pcc','ba']].replace(to_replace={'present':1,'notpresent':0})
#dataset[['appet']] = dataset[['appet']].replace(to_replace={'good':1,'poor':0,'no':np.nan})
#dataset['classification']=dataset['classification'].replace(to_replace={'ckd':1.0,'ckd\t':1.0,'notckd':0.0,'no':0.0})
#dataset.rename(columns={'classification':'class'},inplace=True)

In [14]:
# # Further cleaning
# dataset['pe'] = dataset['pe'].replace(to_replace='good',value=0) # Not having pedal edema is good
# dataset['appet'] = dataset['appet'].replace(to_replace='no',value=0)
# dataset['cad'] = dataset['cad'].replace(to_replace='\tno',value=0)
# dataset['dm'] = dataset['dm'].replace(to_replace={'\tno':0,'\tyes':1,' yes':1, '':np.nan})
# dataset.drop('id',axis=1,inplace=True)

In [15]:
#dataset.head()

In [16]:
# '?' character remove process in the dataset
#for i in ['rc','wc','pcv']:
    #dataset[i] = dataset[i].str.extract('(\d+)').astype(float)

In [17]:
# Filling missing numeric data in the dataset with mean
#for i in ['age','bp','sg','al','su','bgr','bu','sc','sod','pot','hemo','rc','wc','pcv']:
    #dataset[i].fillna(dataset[i].mean(),inplace=True)

In [18]:
#dataset.isnull().sum()

In [19]:
#dataset = dataset.dropna(axis=1)

In [20]:
dataset.head()

bu   sc         sod       pot  hemo   pcv  ...  pcc   ba  htn   dm  cad  class
0  36.0  1.2  138.672705  3.728215  15.4  44.0  ...  0.0  0.0  1.0  1.0  0.0    1.0
1  18.0  0.8  130.739113  3.874993  11.3  38.0  ...  0.0  0.0  0.0  0.0  0.0    1.0
2  53.0  1.8  132.762387  4.944903   9.6  31.0  ...  0.0  0.0  0.0  1.0  0.0    1.0
3  56.0  3.8  111.000000  2.500000  11.2  32.0  ...  1.0  0.0  1.0  0.0  0.0    1.0
4  26.0  1.4  133.960632  3.462571  11.6  35.0  ...  0.0  0.0  0.0  0.0  0.0    1.0

[5 rows x 15 columns]

In [21]:
dataset.shape

(400, 15)

In [22]:
#dataset.isnull().sum()

In [23]:
#dataset.head()

In [24]:
#dataset=dataset.drop('class',1)

In [25]:
#dataset.iloc[:,:-1]

In [26]:
dataset.iloc[:,-1]

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ... 
395    0.0
396    0.0
397    0.0
398    0.0
399    0.0
Name: class, Length: 400, dtype: float64

In [27]:
# Data preprocessing
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [28]:
X

array([[ 36.        ,   1.2       , 138.67270546, ...,   1.        ,
          1.        ,   0.        ],
       [ 18.        ,   0.8       , 130.73911259, ...,   0.        ,
          0.        ,   0.        ],
       [ 53.        ,   1.8       , 132.7623871 , ...,   0.        ,
          1.        ,   0.        ],
       ...,
       [ 26.        ,   0.6       , 137.        , ...,   0.        ,
          0.        ,   0.        ],
       [ 50.        ,   1.        , 135.        , ...,   0.        ,
          0.        ,   0.        ],
       [ 18.        ,   1.1       , 141.        , ...,   0.        ,
          0.        ,   0.        ]])

In [29]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [30]:
from sklearn.model_selection import train_test_split    
from sklearn.preprocessing import MinMaxScaler

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [32]:
X_train.shape

(320, 14)

In [33]:
scaler = MinMaxScaler()

In [34]:
X_test.shape

(80, 14)

In [35]:
y_test.shape

(80,)

In [36]:
y_test

array([1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0.,
       1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0.,
       1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.])

In [37]:
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

In [38]:
# # Reshaping X_train for efficient modelling
# X_train = np.reshape(X_train, (X_train.shape[0],X_train.shape[1],1))
# X_test = np.reshape(X_test, (X_test.shape[0],X_test.shape[1],1))

In [39]:
from keras.models import Sequential
from tensorflow import keras
from keras.layers import Dense, LSTM, Dropout, GRU, Bidirectional
#from keras.optimizers import SGD
import math
from sklearn.metrics import mean_squared_error

In [ ]:
import time
start_time = time.time()
#build the model
# sequential
#3 layers firtst 2 nurons and relu function
#output layer 10 nuron softmax function
model = Sequential()
model.add(keras.layers.Dense (15,input_shape=(X_train.shape[1],),activation='relu')) #input layer
model.add(keras.layers.Dense (10,activation='relu')) #hidden
model.add(keras.layers.Dense (1,activation='sigmoid')) #output
model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)
model.fit(X_train,y_train,epochs=200,validation_data=(X_test, y_test))
print("--- %s seconds ---" % (time.time() - start_time))

Epoch 1/200
10/10 [==============================] - 1s 19ms/step - loss: 0.7326 - accuracy: 0.4437 - val_loss: 0.7234 - val_accuracy: 0.4125
Epoch 2/200
10/10 [==============================] - 0s 3ms/step - loss: 0.7041 - accuracy: 0.4969 - val_loss: 0.6943 - val_accuracy: 0.4750
Epoch 3/200
10/10 [==============================] - 0s 4ms/step - loss: 0.6795 - accuracy: 0.6875 - val_loss: 0.6695 - val_accuracy: 0.6375
Epoch 4/200
10/10 [==============================] - 0s 3ms/step - loss: 0.6578 - accuracy: 0.7656 - val_loss: 0.6462 - val_accuracy: 0.7625
Epoch 5/200
10/10 [==============================] - 0s 3ms/step - loss: 0.6362 - accuracy: 0.8406 - val_loss: 0.6241 - val_accuracy: 0.8500
Epoch 6/200
10/10 [==============================] - 0s 3ms/step - loss: 0.6158 - accuracy: 0.9125 - val_loss: 0.6020 - val_accuracy: 0.9000
Epoch 7/200
10/10 [==============================] - 0s 3ms/step - loss: 0.5944 - accuracy: 0.9438 - val_loss: 0.5795 - val_accuracy: 0.9250
Epoch 8/200


In [ ]:
from keras.utils.vis_utils import plot_model
#plot_model(model, to_file='model_plot_ann_RFE.png')

In [ ]:
# from google.colab import files
# #files.download('model_plot_ann_RFE.png') 

In [ ]:
import matplotlib.pyplot as plt

fig = plt.gcf()
plt.plot(model.history.history['loss'])
plt.plot(model.history.history['val_loss'])
plt.title('ANN_RFE')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend(['loss', 'validation loss'], loc='upper right')
plt.show()
fig.savefig('ANN_RFE.png', dpi=100)

In [ ]:
# from google.colab import files
# files.download('ANN_RFE.png') 

In [ ]:
predictions = model.predict_classes(X_test)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
print(classification_report(y_test,predictions))

In [ ]:
print(confusion_matrix(y_test,predictions))

In [ ]:
cnf_matrix = [[28, 0],[3, 49]]

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

class_names = [0,1]
fig,ax = plt.subplots()
tick_marks = np.arange(len(class_names))
plt.xticks(tick_marks,class_names)
plt.yticks(tick_marks,class_names)

#create a heat map
sns.heatmap(pd.DataFrame(cnf_matrix), annot = True,cmap = 'YlGnBu',
           fmt = 'g')
ax.xaxis.set_label_position('top')
plt.tight_layout()
plt.title('ANN_RFE', y = 1.1)
plt.ylabel('Actual label')
plt.xlabel('Predicted label')
plt.savefig('ANN_RFE_Matrix.png')
plt.show()

In [ ]:
from sklearn.metrics import accuracy_score
first = 0
second = 50
prediction_accuracy = []
for i in range(8):
  X_test_ = dataset.iloc[first:second,:-1].values
  y_true = dataset.iloc[first:second,-1].values

  X_test_  = scaler.transform(X_test_)

  y_pred = model.predict_classes(X_test_)
  accuracy = accuracy_score(y_true, y_pred)
  prediction_accuracy.append(accuracy)

  first = second
  second = second+50
prediction_accuracy

In [ ]:
from sklearn.metrics import roc_curve, auc
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, predictions)
roc_auc = auc(false_positive_rate, true_positive_rate)
roc_auc

In [ ]:
import matplotlib.pyplot as plt
plt.figure(figsize=(10,10))
plt.title('ANN_RFE')
plt.plot(false_positive_rate,true_positive_rate, color='red',label = 'AUC = %0.2f' % roc_auc)
plt.legend(loc = 'lower right')
plt.plot([0, 1], [0, 1],linestyle='--')
plt.axis('tight')
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')


In [ ]:
data = {
    'ANN_false': false_positive_rate,
    'ANN_true': true_positive_rate,
    'ANN_prediction_accuracy': prediction_accuracy
  }

In [ ]:
df = pd.DataFrame.from_dict(data, orient='index')
df = df.transpose()

In [ ]:
df.to_csv('ann_RFE_output.csv', index=False)

In [ ]:
# from google.colab import files
# files.download('ann_RFE_output.csv') 